defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

root_dir: '/home/sebalzer/Documents/TAVI_CT/KARD_IMAGING/CT Strain Zoe/'
in_path: '/home/sebalzer/Documents/TAVI_CT/KARD_IMAGING/CT Strain Zoe/ScreeningListe Zoe Export.xlsx'
out_path: '/home/sebalzer/Documents/TAVI_CT/KARD_IMAGING/CT Strain Zoe/ScreeningListeZoeFilled.xlsx'
out_path_cleaned: '/home/sebalzer/Documents/TAVI_CT/KARD_IMAGING/CT Strain Zoe/ScreeningListeZoeFilledCleaned.xlsx'